### PR TITLE
Component Review for Unit Task List

### PR DESCRIPTION
**Pull request by dylansutherland**
# Description

Pull request for the following component reviews:

- unit-task-list

## Type of change

- [x] Documentation (new)

# How Has This Been Tested?

## Testing Checklist:

- [x] Tested in latest Chrome
- [x] Tested in latest Safari
- [x] Tested in latest Firefox

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

### CODE REVIEW

**Comment by maddernd** [comment]
If we can add some screenshots of how it looks before, and how it will look after the changes to Angular 15.

**Review by macite — APPROVED** [review]
This looks good. Style the new list based on the update task inbox.

**Comment by macite** [comment]
It would be good to see the proposed new design.

**Comment by maddernd** [comment]
Hi Dylan, This one is looking good. We just need to see a mock up off what the new component will look like after conversion. Based on the task inbox.

**Comment by maddernd** [comment]
Please fix the prettier errors 

Run npm run format:check

> format:check
> prettier --check "**/*.md"

Checking formatting...
[warn] docs/OnTrack/UI Enhancement/Component-Review - UnitTaskList.md
[warn] Code style issues found in the above file. Forgot to run Prettier?
Error: Process completed with exit code 1.

**Pull request closed without merging**
