### PR TITLE
Doc/jupyter notebook documentation edits

### PR DESCRIPTION
**Pull request by lachfoy**
# Description
Added new documentation for describing how our solution will be implemented using Docker containers.

Fixes # (issue)
Minor link fixes and delete temporary Epic file which has already been replaced.

## Type of change
- [x] Documentation (update or new)

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have requested a review from @mfclark1 on the Pull Request

### CODE REVIEW

**Comment by talzid** [comment]
@lachfoy is this still intended to be a draft PR?
@mfclark1  slight nudge on the review process

**Comment by lachfoy** [comment]
Hi @talzid  it is somewhat of a work in progress as far as our research goes, but it may be worthwhile to merge anyway.

**Comment by mfclark1** [comment]
This document contains a lot of technical information, so I'm not entirely sure I'm the best candidate to review the changes being made @talzid @lachfoy. Secondly, I don't have write access as far as I'm aware.

It might be worth getting @EthanKeirs to double check this one.

**Review by jordanlitsas — APPROVED** [review]
lgtm

**Pull request merged**
