### PR TITLE
Reports

### PR DESCRIPTION
**Pull request by sivas10**
2 reports are attached:
- demonstration of Trello tasks (analysed Lighthouse reports and extracted tasks and added to Trello board)
- demonstration of upskilling done to contribute to the frontend of the project (improve Lighthouse performance score)

Fixed Prettier errors in all files.

### CODE REVIEW

**Comment by sivas10** [comment]
[Upskill: Learn CSS structures.](https://trello.com/c/0kBcpkYb/151-upskill-learn-css-structures)

**Comment by sivas10** [comment]
[Upskill: Learn vue.js, debugging JavaScript code & how to use docker](https://trello.com/c/D79MEqr5/150-upskill-learn-vuejs-debugging-javascript-code-how-to-use-docker)

**Comment by sivas10** [comment]
[Report on Lighthouse review and associated improvements added in backlog](https://trello.com/c/VWmLun45/154-report-on-lighthouse-review-and-associated-improvements-added-in-backlog)

**Comment by sivas10** [comment]
[Upskill: JavaScript basics with HTML and CSS](https://trello.com/c/7lGVCh1M/103-upskill-javascript-basics-with-html-and-css)

**Comment by sivas10** [comment]
[Write report demonstrating upskilling](https://trello.com/c/jeALQqUS/130-write-report-demonstrating-upskilling)

**Comment by sivas10** [comment]
[Upskill: Learnt TreeShaking, Ant Design, Code Splitting, Webpack usage and Lazy Routing.](https://trello.com/c/zLySlmaa/167-upskill-learnt-treeshaking-ant-design-code-splitting-webpack-usage-and-lazy-routing)

**Comment by chloeehulme** [comment]
Closing this as I have submitted PR on their behalf.

**Pull request closed without merging**
