### PR TITLE
docs:Documentation of AvatarAPI

### PR DESCRIPTION
**Pull request by codeJdawg**
This is documentation of the API file Avatar, its function and its related API files.

JadenDMD@Gmail.com

# Description

This is documentation of the API file AVatar, its function and its related API files.

## Type of change

- [X ] Documentation (update or new)

# How Has This Been Tested?

This is documentation of API files, no testing is required.

# Checklist:

- [X ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by codeJdawg** [comment]
Documentation for API file Avatar_api complete and sent. More will be coming over the rest of the day!

**Comment by Josh-Piper** [comment]
Let me know when this is ready to review. I see that it is still in draft mode.

**Comment by Josh-Piper** [comment]
Couple of questions:
1. Is this code used in the frontend?
2. What problem does this code solve? (it might not if it isnt used etc)

**Comment by codeJdawg** [comment]
Hi Joshua, does that mean that I should add another documentation file to this pull request? 

Also, I believe that this file is mainly for the front end as it requires the user to choose what parameter type they want for their avatar, such as hair, torso, head & accessories. which are extracted from the other Avatar API files.

This code does not solve a problem, but it is used to merge 4 variables from 4 different API files to create a single avatar.

**Comment by Josh-Piper** [comment]
Currently you are documenting all the backend controllers and API's.

These will eventually be hooked into the backend so user's can store their data. So we want to differentiate between the API's that are currently being used by the frontend, and which, are not.

Navigating to https://github.com/thoth-tech/dream-big/tree/main/dream-big-ui/src/app/services I can see that there is a frontend service (Angular services is how Angular sends network calls). BUT, when I search for `AvatarService` within the Dream Big repository I can see it exists within the `avatar-container.component.ts` and is not used. So this means that the frontend is not hooked into this backend API.

Considering this I would make a note like:
`The avatar service is partially implemented in the frontend with a service created. No data is sent to the backend`.

**Comment by Josh-Piper** [comment]
All these comments can be within the same file (the one you have created for this pull request).

We just want to document what current exists within the codebase so the leadership team can glance at the documents and know what is implemented.

On this point, once we have all the documentation it may be worth having a large list of.
1. Implemented APIs for the frontend and backend
2. Partially implemented APIs in the frontend
3. APIs that have not been implemented at all in the frontend

**Comment by codeJdawg** [comment]
Hi Joshua, so I have completed all the documentation for the main API file seen here https://github.com/thoth-tech/dream-big/tree/d72249d788068c71962e5a760ab1e15caef50ce5/dream-big-api/app/api so I think I will be sending them all off today. 

For the list that you mentioned can that be included in the handover as well? Because when I attended my meeting with my tutor yesterday, she mentioned that Thursday is the final day for committing stuff to the repository.

**Comment by Josh-Piper** [comment]
Yup of course, that all works with me.

**Comment by codeJdawg** [comment]
Cool, I think I will be trying to add another documentation file to this request I think? Still quite new to GitHub so I'm trying to work out the best way to send off multiple files at once. Thank you, Joshua.

**Review by Josh-Piper — APPROVED** [review]
Looks good!

**Pull request merged**
