### PR TITLE
add: documentation on behalf of siva

### PR DESCRIPTION
**Pull request by chloeehulme**
_Any italic text should be deleted from the final Pull Request text, including this line_

# Description

_Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change._

Fixes # (issue)

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (update or new)

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration_

## Testing Checklist:

- [ ] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

### CODE REVIEW

**Review by maddernd — APPROVED** [review]

**Comment by sivas10** [comment]
[Review Research from T1 and create Backlog](https://trello.com/c/EFBkUz9u/22-review-research-from-t1-and-create-backlog)

**Comment by sivas10** [comment]
[Write report demonstrating upskilling](https://trello.com/c/jeALQqUS/130-write-report-demonstrating-upskilling)

**Comment by sivas10** [comment]
[Upskill: JavaScript basics with HTML and CSS](https://trello.com/c/7lGVCh1M/103-upskill-javascript-basics-with-html-and-css)

**Comment by sivas10** [comment]
[Upskill: Learn CSS structures.](https://trello.com/c/0kBcpkYb/151-upskill-learn-css-structures)

**Comment by sivas10** [comment]
[Upskill: Learn vue.js, debugging JavaScript code & how to use docker](https://trello.com/c/D79MEqr5/150-upskill-learn-vuejs-debugging-javascript-code-how-to-use-docker)

**Comment by sivas10** [comment]
[Report on Lighthouse review and associated improvements added in backlog](https://trello.com/c/VWmLun45/154-report-on-lighthouse-review-and-associated-improvements-added-in-backlog)

**Comment by sivas10** [comment]
[Upskill: Learnt TreeShaking, Ant Design, Code Splitting, Webpack usage and Lazy Routing.](https://trello.com/c/zLySlmaa/167-upskill-learnt-treeshaking-ant-design-code-splitting-webpack-usage-and-lazy-routing)

**Pull request merged**
