### PR TITLE
docs:added template for project sign off document

### PR DESCRIPTION
**Pull request by maddernd**
# Description

This is a basic template for creating a project sign off with the client.

## Type of change
- [X] Documentation (update or new)

## Testing Checklist:

- [X] Tested in latest Chrome

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have requested a review from ... on the Pull Request

### CODE REVIEW

**Review by maddernd — COMMENTED** [review]
Approved for merge

**Comment by maddernd** [comment]
This looks good.

**Review by maddernd — COMMENTED** [review]
This meets all formatting changes, however the VASE build errors in the test are not related to this pull request.

**Review by macite — CHANGES_REQUESTED** [review]
This looks good, but can we adjust the Vale checks so that the checks pass (if we are happy the issues it raises are not important enough to require addressing)

**Review by macite — APPROVED** [review]

**Pull request merged**
