### PR TITLE
Docs:qa meeting minutes

### PR DESCRIPTION
**Pull request by Fletch99**
# Description

Uploaded and edited the meeting minutes for the first QA and testing meeting.

## Type of change

- [ ] Documentation New

# Checklist:

- [Y] My code follows the style guidelines of this project
- [Y] I have performed a self-review of my own code
- [NA] I have commented my code in hard-to-understand areas
- [Y] I have made corresponding changes to the documentation
- [Y] My changes generate no new warnings
- [Y] I have requested a review from @ShaeChristmas on the Pull Request

### CODE REVIEW

**Review by studioant — CHANGES_REQUESTED** [review]
@Fletch99 Looks fine to me, you will need to run a de-linter and prettier on both docs for them to pass the validation checks. Requesting changes for this reason only.

**Comment by Fletch99** [comment]
> @Fletch99 Looks fine to me, you will need to run a de-linter and prettier on both docs for them to pass the validation checks. Requesting changes for this reason only.

This has been completed

**Review by ShaeChristmas — APPROVED** [review]
Looks good!

**Review by studioant — APPROVED** [review]
Looks good 🎖️

**Pull request merged**
