### PR TITLE
Component 99 Review

### PR DESCRIPTION
**Pull request by sliu0107**
Component 99 Review using the template provided

Sicheng Liu 220579723

# Description

This is the code review of component 99:  all.coffee

## Type of change

_Please delete options that are not relevant._

- [X] Documentation (update or new)

# How Has This Been Tested?

This is just a code review. This component's code only has 3 lines and it is a definition. Nothing really needs to be tested. 

## Testing Checklist:

- [X] Tested in latest Chrome

# Checklist:

- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by maddernd** [comment]
This needs linelint and prettier running on it as its currently failing the tests.

**Comment by sliu0107** [comment]
> This needs linelint and prettier running on it as its currently failing the tests.

Sorry I did not get it. Would you please be a liitle bit more specific about what the problem is so that I can adjust the missing or wrong part of my work

**Comment by maddernd** [comment]
> > This needs linelint and prettier running on it as its currently failing the tests.
> 
> Sorry I did not get it. Would you please be a liitle bit more specific about what the problem is so that I can adjust the missing or wrong part of my work

Run fernandrone/linelint@master
/usr/bin/docker run --name ed866e9fc6baabfb1b49e080a[3](https://github.com/thoth-tech/documentation/actions/runs/4965769626/jobs/8886793198?pr=243#step:4:4)[4](https://github.com/thoth-tech/documentation/actions/runs/4965769626/jobs/8886793198?pr=243#step:4:5)cfb1a7873e[5](https://github.com/thoth-tech/documentation/actions/runs/4965769626/jobs/8886793198?pr=243#step:4:6)_338bc[6](https://github.com/thoth-tech/documentation/actions/runs/4965769626/jobs/8886793198?pr=243#step:4:7) --label ed866e --workdir /github/workspace --rm -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/documentation/documentation":"/github/workspace" ed866e:9fc6baabfb1b49e080a34cfb1a7873e5
No configuration file found at ./.linelint.yml (will use default configuration)
[EOF Rule] File "docs/OnTrack/UI Enhancement/Component99 review.md" has lint errors

Total of 1 lint errors!

**Comment by sliu0107** [comment]
> > > This needs linelint and prettier running on it as its currently failing the tests.
> > 
> > 
> > Sorry I did not get it. Would you please be a liitle bit more specific about what the problem is so that I can adjust the missing or wrong part of my work
> 
> Run fernandrone/linelint@master /usr/bin/docker run --name ed866e9fc6baabfb1b49e080a[3](https://github.com/thoth-tech/documentation/actions/runs/4965769626/jobs/8886793198?pr=243#step:4:4)[4](https://github.com/thoth-tech/documentation/actions/runs/4965769626/jobs/8886793198?pr=243#step:4:5)cfb1a7873e[5](https://github.com/thoth-tech/documentation/actions/runs/4965769626/jobs/8886793198?pr=243#step:4:6)_338bc[6](https://github.com/thoth-tech/documentation/actions/runs/4965769626/jobs/8886793198?pr=243#step:4:7) --label ed866e --workdir /github/workspace --rm -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/documentation/documentation":"/github/workspace" ed866e:9fc6baabfb1b49e080a34cfb1a7873e5 No configuration file found at ./.linelint.yml (will use default configuration) [EOF Rule] File "docs/OnTrack/UI Enhancement/Component99 review.md" has lint errors
> 
> Total of 1 lint errors!

Hi, I have edited the file, Would you please have a check again? Thank you so much

**Comment by sliu0107** [comment]
Please have a check again, thank you!

**Comment by maddernd** [comment]
Run npm run format:check

> format:check
> prettier --check "**/*.md"

Checking formatting...
[warn] docs/OnTrack/UI Enhancement/Component[9](https://github.com/thoth-tech/documentation/actions/runs/5073670261/jobs/9112967576?pr=245#step:7:10)9 review.md
[warn] Code style issues found in the above file. Forgot to run Prettier?
Error: Process completed with exit code 1.

**Comment by maddernd** [comment]
Failed tests

**Pull request closed without merging**
