### PR TITLE
Trimester 1 Cyber Security, Trimester 2 IIF Research and Course Review

### PR DESCRIPTION
**Pull request by DomRyz**
# Description

Added Last Trimester documents along with two new documents for IIIF

## Type of change

- [X ] Documentation (update or new)

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration_

## Testing Checklist:

- [ ] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

### CODE REVIEW

**Comment by maddernd** [comment]
Run sudo apt update

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Hit:1 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:5 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3611 B]
Get:6 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:[7](https://github.com/thoth-tech/documentation/actions/runs/5886615776/job/15964749182?pr=360#step:8:8) http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:[8](https://github.com/thoth-tech/documentation/actions/runs/5886615776/job/15964749182?pr=360#step:8:9) http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [88[9](https://github.com/thoth-tech/documentation/actions/runs/5886615776/job/15964749182?pr=360#step:8:10) kB]
Get:9 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [214 kB]
Get:[10](https://github.com/thoth-tech/documentation/actions/runs/5886615776/job/15964749182?pr=360#step:8:11) http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 c-n-f Metadata [15.6 kB]
Get:[11](https://github.com/thoth-tech/documentation/actions/runs/5886615776/job/15964749182?pr=360#step:8:12) http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [710 kB]
Get:[12](https://github.com/thoth-tech/documentation/actions/runs/5886615776/job/15964749182?pr=360#step:8:13) http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [1[13](https://github.com/thoth-tech/documentation/actions/runs/5886615776/job/15964749182?pr=360#step:8:14) kB]
Get:13 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [967 kB]
Get:[14](https://github.com/thoth-tech/documentation/actions/runs/5886615776/job/15964749182?pr=360#step:8:15) http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [210 kB]
Get:15 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 c-n-f Metadata [21.5 kB]
Get:16 http://azure.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [41.6 kB]
Get:17 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [679 kB]
Hit:18 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
Get:19 http://azure.archive.ubuntu.com/ubuntu jammy-security/main Translation-en [155 kB]
Get:20 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 c-n-f Metadata [11.2 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:22 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [694 kB]
Get:23 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted Translation-en [110 kB]
Get:24 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted amd64 c-n-f Metadata [536 B]
Get:25 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [770 kB]
Get:26 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe Translation-en [140 kB]
Get:27 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 c-n-f Metadata [16.4 kB]
Get:28 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main armhf Packages [9004 B]
Get:29 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [18.1 kB]
Get:30 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [87.2 kB]
Get:31 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [679 kB]
Get:32 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1395 kB]
Get:33 http://security.ubuntu.com/ubuntu jammy-security/main Translation-en [[15](https://github.com/thoth-tech/documentation/actions/runs/5886615776/job/15964749182?pr=360#step:8:16)5 kB]
Get:34 http://security.ubuntu.com/ubuntu jammy-security/main amd64 c-n-f Metadata [11.2 kB]
Get:35 http://archive.ubuntu.com/ubuntu jammy/main Translation-en [510 kB]
Get:36 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [694 kB]
Get:37 http://archive.ubuntu.com/ubuntu jammy/main amd64 c-n-f Metadata [30.3 kB]
Get:38 http://security.ubuntu.com/ubuntu jammy-security/restricted Translation-en [110 kB]
Get:39 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [129 kB]
Get:40 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 c-n-f Metadata [536 B]
Get:41 http://archive.ubuntu.com/ubuntu jammy/restricted Translation-en [18.6 kB]
Get:42 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [770 kB]
Get:43 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 c-n-f Metadata [488 B]
Get:44 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [889 kB]
Get:45 http://security.ubuntu.com/ubuntu jammy-security/universe Translation-en [140 kB]
Get:46 http://archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [214 kB]
Get:47 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 c-n-f Metadata [[16](https://github.com/thoth-tech/documentation/actions/runs/5886615776/job/15964749182?pr=360#step:8:17).4 kB]
Get:48 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [36.5 kB]
Get:49 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 c-n-f Metadata [15.6 kB]
Get:50 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [710 kB]
Get:51 http://security.ubuntu.com/ubuntu jammy-security/multiverse Translation-en [7060 B]
Get:52 http://archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [113 kB]
Get:53 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 c-n-f Metadata [260 B]
Get:54 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 c-n-f Metadata [536 B]
Fetched 13.4 MB in 3s (4892 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
59 packages can be upgraded. Run 'apt list --upgradable' to see them.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
snapd is already the newest version (2.58+[22](https://github.com/thoth-tech/documentation/actions/runs/5886615776/job/15964749182?pr=360#step:8:23).04.1).
snapd set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 59 not upgraded.
vale (edge) 2.15.4 from Joseph Kato (jdkato) installed

> prose:check
> vale --minAlertLevel error --output=docs/.vale/vale.tmpl docs

docs/ArtGallery/IIIF/IIIF Course Review.md:
 Line [56](https://github.com/thoth-tech/documentation/actions/runs/5886615776/job/15964749182?pr=360#step:8:57), position [85](https://github.com/thoth-tech/documentation/actions/runs/5886615776/job/15964749182?pr=360#step:8:86) (rule thothtech.Repetition)
 error: "our" is repeated.
 More information: 

1 errors, 0 warnings, and 0 suggestions found.
Error: Process completed with exit code 1.

**Comment by chloeehulme** [comment]
Please fix the prettier errors!

**Comment by maddernd** [comment]
@DomRyz  please fix this up this week or PR will get closed.

**Comment by chloeehulme** [comment]
Please fix the Vale error :)

**Pull request closed without merging**
