### PR TITLE
docs:dreambig_API doc assessments.md

### PR DESCRIPTION
**Pull request by codeJdawg**
Documentation explaining how assessments API file functions

JadenDMD@Gmail.com

# Description

This is documentation explaining the function of the DreamBig API file: assessments_api.rb
Should there be any possible bug or error found it will be noted within the document.

## Type of change

- [X ] Documentation (update or new)

# How Has This Been Tested?

I am unsure, I am writing documentation of the existing API code for the DreamBig project. This is made in MarkDown format.

## Testing Checklist:

# Checklist:

- [ X] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Josh-Piper** [comment]
This pull request looks great, especially like how you followed the current conventions in creating the pull request!

Is an assessment related to any other models? and if so, can you specify how and why.

Specifically, expanding on how its related to a journey and category (I can tell this by the required parameters).

**Comment by codeJdawg** [comment]
Added some detail for the documentation regarding the assessment parameters journey_id & category_id, regarding how they are related to Journey/Category API files.

**Review by Josh-Piper — APPROVED** [review]
looks great!

**Comment by Josh-Piper** [comment]
Just noticed a CI build failure, you need to run `npm run format`. If this doesn't work, run a `npm install` and then try again. After you have made these changes, feel free to do the merge.

PLEASE, do not merge before this is done.

**Pull request merged**
