### PR TITLE
Arcade Machine Theme + Installation Documentation

### PR DESCRIPTION
**Pull request by RileyOussoren**
# Description

This pull request adds in the files for the Splashkit theme for the Arcade Machine. the theme comes with a parent theme called simple which is a base EmulationStation theme that has been edited to fit with the Splashkit theme, and the sk theme, which is a built up theme entirely designed to represent Splashkit and Thoth tech.

it also includes a change to the Setup arcade machine.md file, explaining how to install the theme, and adds 2 images that are used in the installation documentation.

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation (update)

# How Has This Been Tested?

I have deleted and reinstalled the theme a couple times on my own EmulationStation setup, and Phil Williams has setup and got the theme running on the Raspberry Pi with no issues, the steps to setup and test in have been given in the installation documentation.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have requested a review from Phil WIlliams on the Pull Request

### CODE REVIEW

**Comment by DaGoblin** [comment]
Need to run Linelin prettier and Vale

**Comment by RileyOussoren** [comment]
i have ran the documentation through prettier, vale and linelint.

**Comment by DaGoblin** [comment]
Looks like it's failing LineLint of theme.xml file, I might just try fix this so we can get it committed.

[EOF Rule] File "docs/Splashkit/Applications/Arcade Machines/Arcade Machine Setup/Files/themes/splashkit/sk/theme.xml" has lint errors

**Comment by DaGoblin** [comment]
OK managed to run LineLine on Theme.xml and auto fix with a return at the end strange behaviours it didnt' flag an issue on the existing file, but when I downloaded it manually from GitHub (just the one file) it then flagged may be something strange with linelint and the .XML format

**Comment by DaGoblin** [comment]
Past LineLine error, but now there's a Prettier Error on Setup Arcase Machine.md Mine Fialing for Some Reason if you can have a look.

**Comment by RileyOussoren** [comment]
I have run prettier on the documentation, so i have no idea why its still coming up with prettier errors

**Review by DaGoblin — APPROVED** [review]
Revied Commit, All checks past.
Approved

**Comment by DaGoblin** [comment]
[ES Create Theme for Splashkit](https://trello.com/c/jbybyP9a/35-es-create-theme-for-splashkit)

**Pull request merged**
