### PR TITLE
Cybersecurity documentation 

### PR DESCRIPTION
**Pull request by sivas10**
# Description

Cybersecurity documentation: 
A report for existing features and a report for new features. 
A sample code script of a malware-detection program.

- [/ ] Documentation (update or new) - new

# Checklist:

- [ /] My code follows the style guidelines of this project
- [ /] I have performed a self-review of my own code
- [/ ] I have commented on my code in hard-to-understand areas
- [/ ] My changes generate no new warnings
- [/ ] I have requested a review from ... on the Pull Request

### CODE REVIEW

**Comment by maddernd** [comment]
This needs prettier running on it 

Checking formatting...
[warn] docs/OnTrack/Task Submission & Redesign/Cybersecurity reports/Code Script .md
[warn] docs/OnTrack/Task Submission & Redesign/Cybersecurity reports/Cybersecurity Report (New Features).md
[warn] docs/OnTrack/Task Submission & Redesign/Cybersecurity reports/Cybersecurity Report (Overall).md
[warn] Code style issues found in 3 files. Forgot to run Prettier?
Error: Process completed with exit code 1.

**Comment by sivas10** [comment]
@maddernd Thank you for checking. My files are actually PDFs converted to .md files - there is no code but only text and a sample code script in one of the documents. I'm unable to implement Prettier to these files because they're text only. Is there anything I could do to get this fixed? Thank you.

**Comment by maddernd** [comment]
The text still needs to meet the format using prettier, its not just code.

If I merge this in it will then fail tests for everyone else who try's to make pull requests afterwards.

Prettier and Markdwon lint apply to md documents not just code.

**Comment by sivas10** [comment]
@maddernd  Thank you, I will work on it and change my files. Do I need to submit another pull request with the changes?

**Comment by maddernd** [comment]
You just need to commit the changes once they are made, not need to make a new PR, the commit will update this PR.

**Comment by sivas10** [comment]
@maddernd Thank you so much. I've just made the changes and committed. Do let me know if there's anything else I'm required to do. Thanks

**Comment by maddernd** [comment]
Run npm run format:check

> format:check
> prettier --check "**/*.md"

Checking formatting...
[warn] docs/OnTrack/Task Submission & Redesign/Cybersecurity reports/Code Script 1.md
[warn] docs/OnTrack/Task Submission & Redesign/Cybersecurity reports/Cybersecurity Report 1 (Overall) copy.md
[warn] docs/OnTrack/Task Submission & Redesign/Cybersecurity reports/Cybersecurity Report 2 (New Features) .md
[warn] Code style issues found in 3 files. Forgot to run Prettier?
Error: Process completed with exit code 1.

**Comment by sivas10** [comment]
@maddernd I've made more changes to the files using Prettier. This time I've also run the files on stackedit and had no errors with the formatting. Please let me know if there are any other issues as I can't seem to find any at this point. Thanks

**Comment by maddernd** [comment]
Run npm run format:check

> format:check
> prettier --check "**/*.md"

Checking formatting...
[warn] docs/OnTrack/Task Submission & Redesign/Cybersecurity reports/code-script.md.md
[warn] docs/OnTrack/Task Submission & Redesign/Cybersecurity reports/cybersecurity-report-new-features.md.md
[warn] docs/OnTrack/Task Submission & Redesign/Cybersecurity reports/cybersecurity-report-overall.md.md
[warn] Code style issues found in 3 files. Forgot to run Prettier?
Error: Process completed with exit code 1.

**Comment by sivas10** [comment]
@maddernd Hi, I've checked and couldn't find any format issues with Prettier. Could you tell me what the issue is? I've tried asking around and no one is able to find the issue with my files. I'd appreciate the advice, thank you.

**Comment by maddernd** [comment]
My advise would be to install prettier + plugin within vscode, then highlight the text within your MD files and right click then click format with prettier plus.

Its usually either a . or a space or line at the end of the document that will cause this issue.

**Comment by maddernd** [comment]
Failed tests

**Pull request closed without merging**
