### PR TITLE
ADD: copy workflow

### PR DESCRIPTION
**Pull request by talzid**
Adding workflow files and pull request template

### CODE REVIEW

**Review by tancnle — APPROVED** [review]
Great work @talzid 👍🏼 Looks great to me 🚀 

We might have to rejig the pull request template since there are mostly doc changes in this repo. The same applies to the handbook. We can look at it in future PR.

**Comment by tancnle** [comment]
You can link this PR with the issue and close it automatically when this PR merge using this [integration](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by talzid** [comment]
Closes #5

**Comment by talzid** [comment]
Yes the PR template will need to change
Specifically the testing area, and contents

**Comment by talzid** [comment]
@sksingh2022 slight nudge

**Comment by tancnle** [comment]
I think this PR is important to get merged ASAP. I would help all incoming changes use a consistent format.

@kats8 would you be able to review this, please? 🙏🏼

**Comment by tancnle** [comment]
This change is implementing a similar CI setup as part of this [PR](https://github.com/thoth-tech/handbook/pull/19) in the handbook repository.

**Review by kats8 — APPROVED** [review]

**Comment by kats8** [comment]
Looks good to go, @tancnle

**Pull request merged**
