### PR TITLE
Lighthouse Reports

### PR DESCRIPTION
**Pull request by gxp150**
Reports Read Me
Project Overview
Lighthouse Actions for Art Gallery
Lighthouse Actions for Thoth Tech 

Rhonda Jorgensen

# Description

_Lighthouse Reports for Mobile and Desktop Platforms, Reports Read Me file for frequency and naming convention. Lighthouse Action Report (customised), Lighthouse on-boarding document, Lighthouse Global recommendation report._

Fixes # (issue)

## Type of change

- [X ] Documentation (new)

# How Has This Been Tested?

_Tested in Chrome Developer using Lighthouse and exporting to PDF_

## Testing Checklist:

- [x ] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

# Checklist:

- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [X ] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

### CODE REVIEW

**Comment by gxp150** [comment]
I did execute the Prettier format option on the md file

**Comment by gxp150** [comment]
Addressed formatting.

**Comment by gxp150** [comment]
Will start again

**Comment by sivas10** [comment]
[Reduce impact of third-party code (Desktop app)](https://trello.com/c/zAEjetfh/93-reduce-impact-of-third-party-code-desktop-app)

**Comment by sivas10** [comment]
[Reduce impact of third-party code (Desktop app)](https://trello.com/c/zAEjetfh/93-reduce-impact-of-third-party-code-desktop-app)

**Pull request closed without merging**
