### PR TITLE
docs:DreamBig APi Documentation

### PR DESCRIPTION
**Pull request by codeJdawg**
This is documentation of the main DreamBig API file, how it is related to all other existing API files, and related frontend services.

JadenDMD@Gmail.com

# Description

This is documentation of the Main API file DreamBig.

## Type of change

- [X ] Documentation (update or new)

# How Has This Been Tested?

This is documentation, no testing is required.

# Checklist:

- [X ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Josh-Piper — APPROVED** [review]
Not sure, we'll merge and fix it if there are any issues after!

**Comment by Josh-Piper** [comment]
Can you run prettier on this again, also these PR's have your email in all of them. Can you leave that out unless you want it forever in Deakin's codebase :)

**Review by Josh-Piper — CHANGES_REQUESTED** [review]
See prev comment

**Comment by codeJdawg** [comment]
Hey Joshua, I might just delete this pull request and try again. Do you happen to know how to do this?

**Pull request closed without merging**
